{% set name = "boto3-stubs" %}
{% set version = "1.36.6" %}
{% set lib_version = version.split(".post")[0] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f5ec1a5a6ecb92912903631163482f6ce84f092d5bc36ec08f770700befccc7b

build:
  number: 0
  noarch: python
requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

outputs:
  - name: boto3-stubs
    requirements:
      run:
        - botocore-stubs
        - types-s3transfer
        - typing-extensions >=4.1.0
    build:
      noarch: python
      script:
        - python -m pip install . -vv
    test:
      script: run_test.py
      commands:
        - pip check
      requires:
        - pip
        - python {{ python_min }}


  - name: boto3-stubs-essential
    build:
      noarch: python
    requirements:
      run:
        # <https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#extra-jinja2-functions>
        # <https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#pinning-at-the-recipe-level>
        - {{ pin_subpackage(name, exact=True) }}
        # For the dependencies, use the pin >=MAJOR.MINOR
        - {{ pin_compatible('mypy_boto3_cloudformation', min_pin='x.x') }}
        - {{ pin_compatible('mypy_boto3_dynamodb', min_pin='x.x') }}
        - {{ pin_compatible('mypy_boto3_ec2', min_pin='x.x') }}
        - {{ pin_compatible('mypy_boto3_lambda', min_pin='x.x') }}
        - {{ pin_compatible('mypy_boto3_rds', min_pin='x.x') }}
        - {{ pin_compatible('mypy-boto3-s3', min_pin='x.x') }}
        - {{ pin_compatible('mypy_boto3_sqs', min_pin='x.x') }}
    test:
      script: test_essential.py
      imports:
        - mypy_boto3_cloudformation
        - mypy_boto3_dynamodb
        - mypy_boto3_ec2
        - mypy_boto3_lambda
        - mypy_boto3_rds
        - mypy_boto3_s3
        - mypy_boto3_sqs
      commands:
        - pip check
      requires:
        - pip
        - mypy_boto3_builder
        - python {{ python_min }}
        # ensure pip check works due to lower version of mypy_boto3_builder
        - black <22.0,>=21.9b0
        - pyparsing <3.0.0,>=2.4.7

about:
  home: https://github.com/vemel/mypy_boto3_builder
  summary: Type annotations for boto3 {{ lib_version }}, generated with mypy-boto3-builder
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/vemel/mypy_boto3_builder
  doc_url: https://youtype.github.io/boto3_stubs_docs/

extra:
  recipe-maintainers:
    - maresb
    - thewchan
    - vemel
